const $=s=>document.querySelector(s);const state={user:null,tab:"login",chat:null,chats:[],providers:[],files:[]};
async function api(url,opt={}){const r=await fetch(url,{credentials:"include",headers:{"Content-Type":"application/json",...(opt.headers||{})},...opt});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||"Request failed");return j}
function esc(s){return s.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
async function boot(){try{const j=await api("/api/auth/me");state.user=j.user;showApp();await loadAll()}catch{showAuth()}}
function showAuth(){$("#authView").classList.remove("hidden");$("#appView").classList.add("hidden")}
function showApp(){$("#authView").classList.add("hidden");$("#appView").classList.remove("hidden");$("#userLabel").textContent=state.user.email;if(state.user.role==="admin")$("#adminBtn").classList.remove("hidden")}
document.querySelectorAll("[data-tab]").forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;document.querySelectorAll("[data-tab]").forEach(x=>x.classList.toggle("active",x===b));$("#name").classList.toggle("hidden",state.tab==="login");});
$("#authForm").onsubmit=async e=>{e.preventDefault();$("#authError").textContent="";try{const j=await api(`/api/auth/${state.tab==="login"?"login":"register"}`,{method:"POST",body:JSON.stringify({name:$("#name").value,email:$("#email").value,password:$("#password").value})});state.user=j.user;showApp();await loadAll()}catch(x){$("#authError").textContent=x.message}};
$("#logout").onclick=async()=>{await api("/api/auth/logout",{method:"POST"});location.reload()};
$("#newChat").onclick=async()=>{const j=await api("/api/conversations",{method:"POST"});state.chats.unshift(j.conversation);openChat(j.conversation.id)};
$("#menuBtn").onclick=()=>$(".sidebar").classList.toggle("open");
async function loadAll(){const [c,p]=await Promise.all([api("/api/conversations"),api("/api/providers")]);state.chats=c.conversations;state.providers=p.providers;renderChats();renderModels();if(!state.chats.length){const j=await api("/api/conversations",{method:"POST"});state.chats=[j.conversation]}openChat(state.chats[0].id)}
function renderChats(){$("#chatList").innerHTML=state.chats.map(c=>`<button class="chat-item ${state.chat?.id===c.id?"active":""}" onclick="openChat('${c.id}')">${esc(c.title)}</button>`).join("")}
function renderModels(){const opts=[];for(const p of state.providers)for(const m of p.models||[])if(m.enabled)opts.push(`<option value="${p.id}|${m.id}">${esc(p.name)} — ${esc(m.display_name)}</option>`);$("#modelSelect").innerHTML=opts.length?opts.join(""):`<option value="">No AI model configured</option>`}
async function openChat(id){const j=await api(`/api/conversations/${id}`);state.chat=j.conversation;state.files=j.files;renderChats();$("#chatTitle").textContent=state.chat.title;$("#messages").innerHTML=j.messages.map(m=>`<div class="msg ${m.role}">${esc(m.content)}</div>`).join("")||'<div class="empty"><h2>Start a new chat</h2><p>Upload files or ask the team AI a question.</p></div>';$("#fileList").innerHTML=state.files.map(f=>`<span class="file-pill">${esc(f.original_name)} · ${f.status}</span>`).join("");$(".sidebar").classList.remove("open");$("#messages").scrollTop=999999}
$("#send").onclick=send;$("#input").addEventListener("keydown",e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();send()}});
async function send(){const text=$("#input").value.trim();const selected=$("#modelSelect").value;if(!text||!selected||!state.chat)return;const [providerId,modelId]=selected.split("|");$("#input").value="";addMsg("user",text);const box=addMsg("assistant","");$("#send").disabled=true;try{const r=await fetch(`/api/conversations/${state.chat.id}/messages`,{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({content:text,providerId,modelId})});if(!r.ok)throw new Error((await r.json()).error);const reader=r.body.getReader(),dec=new TextDecoder();let pending="";while(true){const x=await reader.read();if(x.done)break;pending+=dec.decode(x.value,{stream:true});const lines=pending.split("\n");pending=lines.pop()||"";for(const line of lines){if(!line.startsWith("data:"))continue;const d=JSON.parse(line.slice(5));if(d.token){box.textContent+=d.token;$("#messages").scrollTop=999999}if(d.error)throw new Error(d.error)}}}catch(e){box.textContent="Error: "+e.message}finally{$("#send").disabled=false}}
function addMsg(role,text){$("#messages").querySelector(".empty")?.remove();const d=document.createElement("div");d.className=`msg ${role}`;d.textContent=text;$("#messages").appendChild(d);$("#messages").scrollTop=999999;return d}
$("#fileInput").onchange=async e=>{for(const f of [...e.target.files])await uploadFile(f);e.target.value=""};
async function uploadFile(file){if(file.size>350*1024*1024){alert("Maximum file size is 350 MB");return}$("#uploadStatus").textContent=`Uploading ${file.name}…`;try{const s=await api("/api/uploads/start",{method:"POST",body:JSON.stringify({fileName:file.name,fileSize:file.size,contentType:file.type,conversationId:state.chat.id})});const parts=[];for(let n=1;n<=s.parts;n++){const u=await api(`/api/uploads/${s.fileId}/part-url`,{method:"POST",body:JSON.stringify({uploadId:s.uploadId,partNumber:n})});const start=(n-1)*s.partSize,end=Math.min(file.size,start+s.partSize);const rr=await fetch(u.url,{method:"PUT",body:file.slice(start,end)});if(!rr.ok)throw new Error("Part upload failed");parts.push({PartNumber:n,ETag:rr.headers.get("ETag")||""});$("#uploadStatus").textContent=`Uploading ${Math.round(n/s.parts*100)}%`;}await api(`/api/uploads/${s.fileId}/complete`,{method:"POST",body:JSON.stringify({uploadId:s.uploadId,parts})});$("#uploadStatus").textContent="Processing file…";let ready=false;for(let i=0;i<60&&!ready;i++){await new Promise(r=>setTimeout(r,1500));const st=await api(`/api/uploads/${s.fileId}/status`);ready=st.file.status==="ready";if(st.file.status==="failed")throw new Error(st.file.processing_error||"Processing failed")}await openChat(state.chat.id);$("#uploadStatus").textContent=ready?"File ready":"File still processing";}catch(e){$("#uploadStatus").textContent="Upload error: "+e.message}}
$("#adminBtn").onclick=()=>{$("#adminModal").classList.remove("hidden");renderProviders()};$("#closeAdmin").onclick=()=>$("#adminModal").classList.add("hidden");
function renderProviders(){$("#providers").innerHTML=state.providers.map(p=>`<div class="provider-row"><strong>${esc(p.name)}</strong><div class="status">${esc(p.provider_type)} · ${(p.models||[]).map(m=>esc(m.display_name)).join(", ")||"no models"}</div><button onclick="testProvider('${p.id}')">Test</button></div>`).join("")}
window.testProvider=async id=>{const j=await api(`/api/providers/admin/providers/${id}/test`,{method:"POST"});alert(j.success?j.message:"Failed: "+j.message)};
$("#providerForm").onsubmit=async e=>{e.preventDefault();try{await api("/api/providers/admin/providers",{method:"POST",body:JSON.stringify({name:$("#pName").value,providerType:$("#pType").value,baseUrl:$("#pUrl").value||undefined,apiKey:$("#pKey").value,models:$("#pModels").value.split(",").map(x=>x.trim()).filter(Boolean).map(x=>({modelId:x,displayName:x}))})});alert("Provider added");e.target.reset();const p=await api("/api/providers");state.providers=p.providers;renderModels();renderProviders()}catch(x){alert(x.message)}};
document.querySelector('[data-tab="login"]').classList.add("active");$("#name").classList.add("hidden");boot();
